### ISSUE TITLE
Create Car Class with numberOfDoors Field

### ISSUE THREAD

**Issue by Robert-Szlufik-L00188394** [Robert-Szlufik-L00188394/UnitTesting#1]
### Tasks:

Create a new Car class.
- [ ] Add a private member numberOfDoors (type: int) to store the number of doors.
- [ ] Implement a constructor to initialize numberOfDoors.
- [ ] Add a getter method getNumberOfDoors() to return the value of numberOfDoors.
- [ ] Add a setter method setNumberOfDoors(int numberOfDoors) to update the value of numberOfDoors.
