### ISSUE TITLE
Add Unit Test for getNumberOfDoors Method

### ISSUE THREAD

**Issue by Robert-Szlufik-L00188394** [Robert-Szlufik-L00188394/UnitTesting#2]
### Tasks:

- [ ] Create a unit test class CarTest.
- [ ] Write a test method testGetNumberOfDoors to verify that the getNumberOfDoors() method returns the correct value when the Car is created.
- [ ] Use assertions to verify the behavior.
